"""Add is_active to users

Revision ID: 6ce4e26d67bc
Revises: 
Create Date: 2026-07-04 10:10:46.402219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ce4e26d67bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('contribution_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('paid_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('amount',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('contributions_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('contributions_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'groups', ['group_id'], ['id'])
        batch_op.drop_column('date')
        batch_op.drop_column('cycle_id')
        batch_op.drop_column('member_id')
        batch_op.drop_column('contribution_id')

    with op.batch_alter_table('cycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cycle_number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('cycles_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['group_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('name')
        batch_op.drop_column('cycle_id')

    with op.batch_alter_table('groupadmin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('permissions', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('username'))
        batch_op.create_foreign_key(None, 'users', ['admin_id'], ['id'])
        batch_op.create_foreign_key(None, 'groups', ['group_id'], ['id'])
        batch_op.drop_column('name')
        batch_op.drop_column('username')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    with op.batch_alter_table('groupmembers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(batch_op.f('groupmembers_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('groupmembers_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['group_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('member_id')
        batch_op.drop_column('date_joined')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('group_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('max_members', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['group_code'])
        batch_op.drop_constraint(batch_op.f('groups_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.drop_column('group_id')
        batch_op.drop_column('date_created')
        batch_op.drop_column('admin_id')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('joined_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.drop_index(batch_op.f('email'))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'groups', ['group_id'], ['id'])
        batch_op.drop_column('member_id')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('email')
        batch_op.drop_column('date_registered')
        batch_op.drop_column('name')
        batch_op.drop_column('password')

    with op.batch_alter_table('savings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('savings_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('active', 'completed', 'paused'),
               type_=sa.String(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'"))
        batch_op.drop_constraint(batch_op.f('savings_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('savings_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['group_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('member_id')
        batch_op.drop_column('savings_id')
        batch_op.drop_column('cycle_id')
        batch_op.drop_column('plan_id')
        batch_op.drop_column('plan_name')
        batch_op.drop_column('target')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('savings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target', mysql.DECIMAL(precision=15, scale=2), nullable=False))
        batch_op.add_column(sa.Column('plan_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('plan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cycle_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('savings_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('member_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('savings_ibfk_2'), 'cycles', ['cycle_id'], ['cycle_id'])
        batch_op.create_foreign_key(batch_op.f('savings_ibfk_1'), 'members', ['member_id'], ['member_id'])
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('active', 'completed', 'paused'),
               nullable=False,
               existing_server_default=sa.text("'active'"))
        batch_op.drop_column('created_at')
        batch_op.drop_column('due_date')
        batch_op.drop_column('description')
        batch_op.drop_column('savings_type')
        batch_op.drop_column('amount')
        batch_op.drop_column('group_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('id')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('date_registered', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('member_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.drop_column('status')
        batch_op.drop_column('joined_date')
        batch_op.drop_column('role')
        batch_op.drop_column('group_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('id')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('date_created', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('groups_ibfk_1'), 'groupadmin', ['admin_id'], ['admin_id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('created_by')
        batch_op.drop_column('is_active')
        batch_op.drop_column('max_members')
        batch_op.drop_column('group_code')
        batch_op.drop_column('description')
        batch_op.drop_column('id')

    with op.batch_alter_table('groupmembers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_joined', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('member_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('groupmembers_ibfk_2'), 'members', ['member_id'], ['member_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('groupmembers_ibfk_1'), 'groups', ['group_id'], ['group_id'], ondelete='CASCADE')
        batch_op.drop_column('is_active')
        batch_op.drop_column('joined_at')
        batch_op.drop_column('role')
        batch_op.drop_column('user_id')
        batch_op.drop_column('id')

    with op.batch_alter_table('groupadmin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('permissions')
        batch_op.drop_column('group_id')
        batch_op.drop_column('id')

    with op.batch_alter_table('cycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cycle_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cycles_ibfk_1'), 'groups', ['group_id'], ['group_id'], ondelete='CASCADE')
        batch_op.alter_column('end_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('amount')
        batch_op.drop_column('cycle_number')
        batch_op.drop_column('user_id')
        batch_op.drop_column('id')

    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contribution_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('member_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cycle_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('date', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('contributions_ibfk_1'), 'members', ['member_id'], ['member_id'])
        batch_op.create_foreign_key(batch_op.f('contributions_ibfk_2'), 'cycles', ['cycle_id'], ['cycle_id'])
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=15, scale=2),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('paid_date')
        batch_op.drop_column('due_date')
        batch_op.drop_column('status')
        batch_op.drop_column('contribution_type')
        batch_op.drop_column('group_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
